# Generated by Django 4.2.29 on 2026-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsignal",
            name="rule",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор правила стратегии (см. strategy_rules.json)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="agentanalysis",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("reasoning_step", "Шаг рассуждения"),
                    ("volume_anomaly", "Аномалия объёма"),
                    ("poc_hvn", "POC/HVN"),
                    ("zone_near", "Рядом с зоной"),
                    ("custom", "Прочее"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
    ]
