# Generated by Django 4.2.29 on 2026-03-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_add_agent_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="run_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("analysis", "Анализ"),
                    ("training", "Обучение"),
                    ("demo", "Демо"),
                    ("live", "Live"),
                ],
                default="analysis",
                max_length=16,
            ),
        ),
    ]
